#!/bin/sh

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^(main|hotfix|bugfix|feature)/[a-zA-Z0-9\-]+$'

message="Please check your branch name."

if ! echo "$local_branch_name" | grep -Eq "$valid_branch_regex"; then
    echo "\033[0;31m$message"
    exit 1
fi

exit 0

